#!/bin/bash
TITLE="ETC. gitconfig and copy scripts"

# echo 0 --> signal of install requirements
# echo 1 --> signal of requirements are already installed 
has_requirements() {
	echo 1
}

# be called if has_requirements() echoes 0.
__NEED_SUDO=1
install_requirements() {
	:
}

__NEED_REBOOT=0
__NEED_RELOGIN=0
ins() {
	mkdir -pv bak
	for dotfile in gitconfig; do
		[ -e ~/."$dotfile" ] && [ ! -L ~/."$dotfile" ] && mv -v ~/."$dotfile" bak/"$dotfile"
		ln -sfv "$BASE/$dotfile" ~/."$dotfile"
	done

	# scripts
	mkdir -p ~/.local/bin
	for bin in bin/*; do
		ln -sfv "$BASE/$bin" ~/.local/bin/
	done
}
