#!/bin/bash
TITLE="Packages"

# echo 0 --> signal of install requirements
# echo 1 --> signal of requirements are already installed 
has_requirements() {
	echo 0
}

# be called if has_requirements() echoes 0.
__NEED_SUDO=1
install_requirements() {
	sudo apt-get install -y git vim curl openssh-server exuberant-ctags
}

__NEED_REBOOT=0
__NEED_RELOGIN=0
ins() {
	:

}
