#!/bin/bash
TITLE="Input Method : Nimf"

# echo 0 --> signal of install requirements
# echo 1 --> signal of requirements are already installed 
has_requirements() {
    echo $(is_pkg_installed nimf)
}

# be called if has_requirements() echoes 0.
__NEED_SUDO=1
install_requirements() {
	sudo add-apt-repository ppa:hodong/nimf
	sudo apt update
	sudo apt-get install -y nimf nimf-libhangul
}

__NEED_REBOOT=0
__NEED_RELOGIN=0
ins() {
	im-config -n nimf
	echo "한글입력기 nimf가 적용되었습니다. 기본 한영 전환키는 Ctrl+Space 입니다."
	echo "nimf-settings 에서 한영전환키를 설정할 수 있습니다."
}
