#!/bin/bash
TITLE="D2Coding Font"

# echo 0 --> signal of install requirements
# echo 1 --> signal of requirements are already installed 
has_requirements() {
	echo 1
}

# be called if has_requirements() echoes 0.
__NEED_SUDO=0
install_requirements() {
	:
}

__NEED_REBOOT=0
__NEED_RELOGIN=0
ins() {
	mkdir -p ~/.fonts
	cp ./fonts/D2Coding/* ~/.fonts
	fc-cache

	if [ -e ~/.fonts/D2Coding Nerd Font Complete.ttf ]; then
		gsettings set org.gnome.desktop.wm.preferences titlebar-font 'D2Coding Nerd Font Bold 13'
		gsettings set org.gnome.desktop.interface font-name 'D2Coding Nerd Font 11'
		gsettings set org.gnome.desktop.interface document-font-name 'D2Coding Nerd Font 11'
		gsettings set org.gnome.desktop.interface monospace-font-name 'D2Coding Nerd Font 13'
	fi

}

