#!/bin/bash
TITLE="Tmux"

# echo 0 --> signal of install requirements
# echo 1 --> signal of requirements are already installed 
has_requirements() {
    echo $(is_pkg_installed tmux)
}

# be called if has_requirements() echoes 0.
__NEED_SUDO=1
install_requirements() {
    sudo apt-get install -y tmux
}

__NEED_REBOOT=0
__NEED_RELOGIN=0
ins() {
	if [ ! -L ~/.tmux.conf ] ; then
		echo "backup tmux.conf..." >&2
		mkdir -pv bak
		mv -v ~/.tmux.conf bak/tmux.conf
	fi

	ln -sfv $BASE/tmux.conf ~/.tmux.conf
}
