#!/bin/bash
TITLE="Gnome"

# echo 0 --> signal of install requirements
# echo 1 --> signal of requirements are already installed 
has_requirements() {
    echo $(is_pkg_installed gnome-tweaks gnome-shell-extensions)
}

# be called if has_requirements() echoes 0.
__NEED_SUDO=1
install_requirements() {
	sudo apt-get install -y gnome-tweaks gnome-shell-extensions
}

__NEED_REBOOT=0
__NEED_RELOGIN=1
ins() {
	install_theme
	install_gnome_extensions
	#setup_proxy
}

install_theme() {
	echo "=============================="
	echo "installing theme..."
	echo "=============================="
	git clone https://github.com/vinceliuice/Qogir-theme.git
	cd Qogir-theme
	./install.sh -t ubuntu -c dark -w standard
	cd ..

	git clone https://github.com/vinceliuice/Qogir-icon-theme.git
	cd Qogir-icon-theme
	./install.sh
	cd ..

	gsettings set org.gnome.desktop.interface gtk-theme "Qogir-ubuntu-dark"
	gsettings set org.gnome.desktop.wm.preferences button-layout appmenu:minimize,maximize,close
	gsettings set org.gnome.desktop.interface icon-theme "Qogir-ubuntu-dark"
	gsettings set org.gnome.shell.extensions.user-theme name "Qogir-ubuntu-dark"
	gsettings set org.gnome.shell enabled-extensions "['user-theme@gnome-shell-extensions.gcampax.github.com']"
}

install_gnome_extensions() {
	echo "=============================="
	echo "installing gnome extensions..."
	echo "=============================="
	# Applications Menu
	#./bin/gnomeshell-extension-manage --install --extension-id 6 
	# removeable drive menu
	./bin/gnomeshell-extension-manage --install --extension-id 7 
	# coverflow alt-tab
	./bin/gnomeshell-extension-manage --install --extension-id 97 
	# System monitor
	if [ $(chk_and_ins_pkgs gir1.2-gtop-2.0 gir1.2-networkmanager-1.0 gir1.2-clutter-1.0) ]; then
		./bin/gnomeshell-extension-manage --install --extension-id 120
		gsettings --schemadir ~/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/schemas/ set org.gnome.shell.extensions.system-monitor icon-display false
		gsettings --schemadir ~/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/schemas/ set org.gnome.shell.extensions.system-monitor move-clock true 
		gsettings --schemadir ~/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/schemas/ set org.gnome.shell.extensions.system-monitor center-display true

		gsettings --schemadir ~/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/schemas/ set org.gnome.shell.extensions.system-monitor cpu-display true
		gsettings --schemadir ~/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/schemas/ set org.gnome.shell.extensions.system-monitor cpu-style 'digit'
		gsettings --schemadir ~/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/schemas/ set org.gnome.shell.extensions.system-monitor cpu-refresh-time 1500

		gsettings --schemadir ~/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/schemas/ set org.gnome.shell.extensions.system-monitor memory-display true
		gsettings --schemadir ~/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/schemas/ set org.gnome.shell.extensions.system-monitor memory-style 'digit'
		gsettings --schemadir ~/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/schemas/ set org.gnome.shell.extensions.system-monitor memory-refresh-time 5000

		gsettings --schemadir ~/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/schemas/ set org.gnome.shell.extensions.system-monitor net-display true
		gsettings --schemadir ~/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/schemas/ set org.gnome.shell.extensions.system-monitor net-style 'digit'
		gsettings --schemadir ~/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/schemas/ set org.gnome.shell.extensions.system-monitor net-refresh-time 1500

		gsettings --schemadir ~/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/schemas/ set org.gnome.shell.extensions.system-monitor disk-display true
		gsettings --schemadir ~/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/schemas/ set org.gnome.shell.extensions.system-monitor disk-style 'digit'
		gsettings --schemadir ~/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/schemas/ set org.gnome.shell.extensions.system-monitor disk-refresh-time 1500
	fi

	# Dash to dock
	./bin/gnomeshell-extension-manage --install --extension-id 307
	gsettings --schemadir ~/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/schemas/ set org.gnome.shell.extensions.dash-to-dock dock-position 'BOTTOM'
	gsettings --schemadir ~/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/schemas/ set org.gnome.shell.extensions.dash-to-dock dash-max-icon-size 32

	# coffeine
	./bin/gnomeshell-extension-manage --install --extension-id 517 
	# Weather
	#./bin/gnomeshell-extension-manage --install --extension-id 750
	# clipboard indicator
	./bin/gnomeshell-extension-manage --install --extension-id 779 
	# Bing Wallpaper Changer
	./bin/gnomeshell-extension-manage --install --extension-id 1262
}


setup_proxy() {
	echo "=============================="
	echo "Setup proxies auto..."
	echo "=============================="
	PROXY_ADDR=""
	PROXY_PORT=""
	PAC_ADDR=""
	gsettings set org.gnome.system.proxy.http host "$PROXY_ADDR"
	gsettings set org.gnome.system.proxy.http port "$PROXY_PORT"
	gsettings set org.gnome.system.proxy.https host "$PROXY_ADDR"
	gsettings set org.gnome.system.proxy.https port "$PROXY_PORT"
	#gsettings set org.gnome.system.proxy mode "manual"
	gsettings set org.gnome.system.proxy autoconfig-url "$PAC_ADDR"
	#gsettings set org.gnome.system.proxy mode "auto"

	echo "ok"
}
