#!/bin/bash
TITLE="Aliases"

# echo 0 --> signal of install requirements
# echo 1 --> signal of requirements are already installed 
has_requirements() {
	echo 1
}

# be called if has_requirements() echoes 0.
__NEED_SUDO=0
install_requirements() {
	:
}

__NEED_REBOOT=0
__NEED_RELOGIN=0
ins() {
	FILE="aliases"
	mkdir -p bak
	[ -f ~/.$FILE ] && [ ! -L ~/."$FILE" ] && mv -v ~/.$FILE bak/$FILE
	cp -v $BASE/$FILE ~/.$FILE
    source ~/.aliases

	update_config=1
	file_name="~/.$FILE"

	append_line $update_config "[ -f $file_name ] && source $file_name" "$HOME/.bashrc" "$file_name"
	append_line $update_config "[ -f $file_name ] && source $file_name" "$HOME/.zshrc" "$file_name"
}

